MD_EXTENSIONS = {
    'abbr': 'Abbreviations',
    'admonition': 'Support admonitions',
    'attr_list': 'Add attribute to HTML tags',
    'codehilite': 'Add code highlighting via Pygments',
    'def_list': 'Definition lists',
    'extra': 'Enables various common extensions',
    'fenced_code': 'Alternative code block syntax',
    'footnotes': 'Footnotes',
    'legacy_attrs': 'Use legacy element attributes',
    'legacy_em': 'Use legacy underscore handling for connected words',
    'meta': 'Meta data',
    'nl2br': 'New line to break',
    'sane_lists': 'Sane lists',
    'smarty': 'Smarty',
    'tables': 'Tables',
    'toc': 'Table of Contents',
    'wikilinks': 'Wiki links',
}
